#!/bin/sh
set -e

echo "============================================"
echo "  LifeHub Backend Starting"
echo "============================================"

# Wait for database to be ready (simple TCP check via node net)
echo "[0/3] Waiting for database..."
MAX_RETRIES=30
for i in $(seq 1 $MAX_RETRIES); do
  if node -e "
    const net = require('net');
    const s = net.createConnection(5432, 'postgres');
    s.on('connect', () => { s.end(); process.exit(0); });
    s.on('error', () => { process.exit(1); });
    setTimeout(() => { process.exit(1); }, 2000);
  " 2>/dev/null; then
    echo "  Database is ready!"
    break
  fi
  echo "  Attempt $i/$MAX_RETRIES - waiting..."
  sleep 2
  if [ $i -eq $MAX_RETRIES ]; then
    echo "  WARNING: Database not reachable after $MAX_RETRIES attempts. Starting anyway..."
  fi
done

# Run database migrations
MIGRATION_DIR="./apps/backend/drizzle"
if [ -d "$MIGRATION_DIR" ]; then
  echo "[1/3] Running database migrations..."
  cd apps/backend
  npx tsx src/db/migrate.ts || echo "  WARNING: Migration skipped or failed (non-fatal)"
  cd /app
else
  echo "[1/3] No migration directory found, skipping."
fi

# JWT keys are auto-generated by shared/auth/src/jwt.ts if not provided via ENV
# They are stored in LIFEHUB_DATA_PATH/keys/ (persistent via volume mount)
echo "[2/3] JWT keys: auto-generated if missing (stored in /data/keys/)"

# Start API server
echo "[3/3] Starting API server..."
exec node apps/backend/dist/apps/backend/src/main.js
