#!/bin/sh
set -e

echo "============================================"
echo "  LifeHub Backend Starting"
echo "============================================"

# Wait for database (simple TCP check via node net)
echo "[0/3] Waiting for database..."
MAX_RETRIES=30
for i in $(seq 1 $MAX_RETRIES); do
  if node -e "
    const net = require('net');
    const s = net.createConnection(5432, 'postgres');
    s.on('connect', () => { s.end(); process.exit(0); });
    s.on('error', () => { process.exit(1); });
    setTimeout(() => { process.exit(1); }, 2000);
  " 2>/dev/null; then
    echo "  Database is ready!"
    break
  fi
  echo "  Attempt $i/$MAX_RETRIES - waiting..."
  sleep 2
  if [ $i -eq $MAX_RETRIES ]; then
    echo "  WARNING: Database not reachable after $MAX_RETRIES attempts. Starting anyway..."
  fi
done

# Run database migrations (CommonJS script, kein tsx nötig)
echo "[1/3] Running database migrations..."
node apps/backend/scripts/migrate.cjs || echo "  WARNING: Migration skipped or failed (non-fatal)"

# JWT keys are auto-generated by shared/auth/src/jwt.ts if not provided via ENV
echo "[2/3] JWT keys: auto-generated if missing (stored in /data/keys/)"

# Start API server
echo "[3/3] Starting API server..."
exec node apps/backend/dist/apps/backend/src/main.js
