-- Migration: Add filename column to media_files (schema drift fix)
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS filename TEXT NOT NULL DEFAULT '';
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS relative_path TEXT NOT NULL DEFAULT '';
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS exif_data JSONB;
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS gps_lat TEXT;
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS gps_lng TEXT;
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS taken_at TIMESTAMPTZ;
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS blur_hash TEXT;
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS auto_index BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE media_files ADD COLUMN IF NOT EXISTS last_indexed_at TIMESTAMPTZ;

ALTER TABLE media_files ADD COLUMN IF NOT EXISTS file_size BIGINT;
ALTER TABLE media_sources ADD COLUMN IF NOT EXISTS filename TEXT NOT NULL DEFAULT '';
ALTER TABLE media_sources ADD COLUMN IF NOT EXISTS relative_path TEXT;
ALTER TABLE media_sources ADD COLUMN IF NOT EXISTS exif_data JSONB;
ALTER TABLE media_sources ADD COLUMN IF NOT EXISTS gps_lat TEXT;
ALTER TABLE media_sources ADD COLUMN IF NOT EXISTS gps_lng TEXT;
ALTER TABLE media_sources ADD COLUMN IF NOT EXISTS taken_at TIMESTAMPTZ;
ALTER TABLE media_sources ADD COLUMN IF NOT EXISTS blur_hash TEXT;
ALTER TABLE media_sources ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE media_sources ADD COLUMN IF NOT EXISTS auto_index BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE media_sources ADD COLUMN IF NOT EXISTS last_indexed_at TIMESTAMPTZ;
